### ISSUE TITLE
Image previews from blog post

### ISSUE THREAD

**Issue by g3cko** [vickylaiio/hugo-theme-introduction#5]
Hello,  

I came across your theme and am taking a quick pass through it - how hard would it be to have each post define a 'preview' image to show in the "latest blog" post section?  I am really new to hugo so I have nothing to base this on, but it didn't sound like this should be too hard... but I did fail in actually doing this myself hah.  

I know I would need to modify the blogsection.html but I haven't figured out how to define/use an image in each blog.md file 

Thanks !
-Aaron

**Comment by vickylaiio** [comment]
In short: if you know your way around Hugo it's not too tough. You'll need a line in your post's front matter for the image URL, and a line in the page HTML that references it using something like `{{ .Site.BaseURL }}{{ .Params.thumbnail }}`.

https://gohugo.io/content/archetypes/#step-1-creating-an-archetype
https://gohugo.io/content/front-matter/#optional-variables

I can implement this in Introduction if there's enough interest, though personally I think it conflicts with the minimalist aesthetic.

**Comment by g3cko** [comment]
Ahh!  It looks like I wasn't understanding how to reference any variables I add to the front matter, they are added to Params.  I have it working now, thanks ! 

My blog posts are mostly image based so I wanted to try to get a preview image for each post, as I don't usually write much - but we'll see if I end up liking how it works out  :)

**Comment by vickylaiio** [comment]
Drop me a link once you've got it running, I'd love to see it! :)
