### ISSUE TITLE
about.md shows up as a blog post when following intro instructions

### ISSUE THREAD

**Issue by fool** [vickylaiio/hugo-theme-introduction#9]
Walking through your startup instructions (thank you for providing them!) a friend and I both come across the same issue:

`hugo new contact.md` does the right thing in the footer - the  contact info is shown:

![image](https://cloud.githubusercontent.com/assets/229024/26663781/ec61fd8e-4641-11e7-8af9-4bad8f22f553.png)

However, it also creates something that looks like a blog post on the front page:

![image](https://cloud.githubusercontent.com/assets/229024/26663787/f9b50418-4641-11e7-8e60-01e0d9ccd6ed.png)

Interestingly, it doesn't actually show up as a blog post when you go the blog section at /blog/.

We use hugo v 0.21 on windows and osx with the same effect.

Any thoughts on why this happens or how to fix?  

cc @kristenpdx (who is the friend I'm working through this with :))

**Comment by vickylaiio** [comment]
Thank you for the excellent issue description :)

Latest Post section was calling all pages except just blog section pages. Fixed now, please `git pull origin master` in your local repo.
